server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm-crud?useSSL=false&useUnicode=true&character=utf-8&serverTimezone=UTC
    username: root
    password: 654321
#关闭templates模板缓存
  thymeleaf:
    cache: false
#配置国际化
  messages:
    basename: i18n.login
#分页插件的配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
